Updated DiffinDiff_HISP.Rmd
Tidy models was failing to load owing to the following error:
Error: package or namespace load failed for ‘tidymodels’...
namespace ‘rlang’ 1.1.4 is already loaded, but >= 1.1.5 is required

Therefore, added a comment before loading libraries to allow people to delete rlang before installing the newest version.